name: UnitTests
on:
  pull_request:
  push:

jobs:
  rpmlinter:
    runs-on: docker
    steps:
    - uses: actions/checkout@v4

    - name: rpmlinter
      run: |
        make spec
        docker run -v "$PWD"/python-boto.spec:/specs/python-boto.spec:z ubun/rpmlinter

  python_test:
    runs-on: docker
    strategy:
      matrix:
        images-tag: [ 3.6.10-alpine3.11 ]
        include:
          - images-tag: 3.6.10-alpine3.11
            python-version: 3.6
    container:
      image: ${{ vars.REGISTRY_HOST }}/${{ vars.REGISTRY_PROJECT }}/python:${{ matrix.images-tag }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Python ${{ matrix.python-version }} dependencies
      run: |
        python${{ matrix.python-version }} -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run tests
      run: |
        source .venv/bin/activate
        python tests/test.py default
